### ISSUE TITLE
Build the official docker image

### ISSUE THREAD

**Issue by tobegit3hub** [zhihu/kids#33]
Currently we have to re-build the docker image manual. I think it would better to provide the official image so that I can simply run `docker run -d -p 3388:3388 zhihu/kids`.

Refer to https://github.com/zhihu/kids#using-docker.

**Comment by liyichao** [comment]
Actually, the server address in `agent.conf` has to be modified according to your environment, thus making the copying conf step necessary.

It has to be done only once, then you can deploy the image via docker hub or your private registry.
An alternative may be building an image and add a config file via `docker run -d -v /path/to/conf:/etc/kids.conf zhihu/kids`, however, you have the overhead of managing the config.

**Comment by liyichao** [comment]
Does that answer your question? If not, please comment why, or I'll close the issue.

**Comment by tobegit3hub** [comment]
@liyichao Sorry for replying late.

I think it would be better to provide the default `agent.conf` which can run in localhost. `docker run -d -v /path/to/conf:/etc/kids.conf zhihu/kids` is great for anyone to specify his or her configuration.

Feel free to close it if you can't provide the official image for developers. But do it if you can and re-building it with the source is quite dumb actually.

**Comment by liyichao** [comment]
fix in https://github.com/zhihu/kids/pull/38

**Comment by liyichao** [comment]
Refer to QuickStart/Using Docker to see how to run kids locally in a container.
