### ISSUE TITLE
between the agents on different hosts, any data compression applied?

### ISSUE THREAD

**Issue by thekiki** [zhihu/kids#43]
we are investigating kids system, looks quite promising. just wondering if data compression supported when agents sending data to another agent/server?

since log data probably contains quite a lot duplicated msg, I think data compression would be very helpful.

thanks!

**Comment by dccmx** [comment]
Currently no, and I don't think it is a good idea to do so. log is usually shot text that one TCP package can carry. In this situation, compression will not worth the cost of CPU usage I think. It is good idea if bulk transfer is introduced. But, kids is designed to be real-time. So bulk transfer is not on the TODO list.

**Comment by thekiki** [comment]
maybe I misunderstand the kids configuration. 

as the example shown, `store buffer` -> `store network` should be a typical use case when transferring log data between different hosts. looks like you buffer logs before send them out. compress one log line is meaningless while compress the whole buffer is another story.

is it possible to do so?

**Comment by dccmx** [comment]
Buffer store is a abstract store. When primary store (usally network store) is not usable, the secondary store is used as a buffer. Then when primary store comes back, data was moved back to primary store. There is no log-level buffer when sending log between nodes using network store.

**Comment by thekiki** [comment]
ah, get it.

you are correct, thanks for the rapid reply.
