### ISSUE TITLE
是否有性能测试报告？

### ISSUE THREAD

**Issue by yfnick** [zhihu/kids#46]
kids是否有做详细的性能测试分析？我在两台内网机器上分别部署了kids，一台做agent，另一台做server，agent端跑echo2kids程序，server端跑subscribe程序，agent端内存不停地往上飙，CPU占100%~

**Comment by liyichao** [comment]
echo2kids 程序本身不适合做为 agent，只是一个示例程序，它的逻辑决定了会 100%~

**Comment by liyichao** [comment]
我们用 https://github.com/zhihu/kids/blob/master/client/c/sample/loggen.c  + kids server 放在两台机器上简单测试过，数据已经不太记得了。
就生产环境的数据看，几百台服务器，每台服务器一个 kids agent ，一个 kids server，server 8 线程，qps 能到 8w。
