### ISSUE TITLE
docker build 错误 [ `doc/Makefile.in' not found]

### ISSUE THREAD

**Issue by leonisliu** [zhihu/kids#48]
[root@localhost kids]# docker build -t zhihu/kids .
Sending build context to Docker daemon 1.031 MB
Sending build context to Docker daemon
Step 0 : FROM debian:wheezy
 ---> b3d362b23ec1
Step 1 : MAINTAINER Li Yichao <liyichao.good@gmail.com>
 ---> Using cache
 ---> ea4ce3653add
Step 2 : COPY ./docker/sources.list /etc/apt/sources.list
 ---> Using cache
 ---> ffe4209fc1a8
Step 3 : RUN apt-get update &&  apt-get install -y --no-install-recommends      build-essential       libtool  automake
 ---> Using cache
 ---> fa15d470609a
Step 4 : WORKDIR /kids
 ---> Using cache
 ---> b79173be6352
Step 5 : COPY . /kids
 ---> Using cache
 ---> 2bcbbeb3db40
Step 6 : RUN ./autogen.sh && ./configure && make
 ---> Running in 6b3b4fff6928
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force
autoreconf: configure.ac: tracing
autoreconf: configure.ac: adding subdirectory deps/ae to autoreconf
autoreconf: Entering directory `deps/ae'
autoreconf: configure.ac: not using Libtool
autoreconf: running: /usr/bin/autoconf --force
autoreconf: running: /usr/bin/autoheader --force
autoreconf: running: automake --add-missing --copy --force-missing
configure.ac:9: installing `./ar-lib'
configure.ac:3: installing `./install-sh'
configure.ac:3: installing `./missing'
Makefile.am: installing `./depcomp'
autoreconf: Leaving directory `deps/ae'
configure.ac:15: installing `./compile'
configure.ac:19: installing `./config.guess'
configure.ac:19: installing `./config.sub'
configure.ac:4: installing `./install-sh'
configure.ac:4: installing `./missing'
src/Makefile.am: installing `./depcomp'
configure.ac:83: required file `doc/Makefile.in' not found
configure.ac:83: required file `test/Makefile.in' not found
Makefile.am:1: required directory ./doc does not exist
Makefile.am:1: required directory ./test does not exist
autoreconf: automake failed with exit status: 1
INFO[0010] The command [/bin/sh -c ./autogen.sh && ./configure && make] returned a non-zero code: 1

**Comment by dccmx** [comment]
@liyichao

**Comment by leonisliu** [comment]
呃，什么意思？里边没有啊？

发自我的 iPhone

**Comment by liyichao** [comment]
Fix in https://github.com/zhihu/kids/pull/49.
