### ISSUE TITLE
master在PutMessage的时候循环对一个worker通知了多次

### ISSUE THREAD

**Issue by si-tech** [zhihu/kids#52]
master在PutMessage的时候，是这样的：
for (auto it : workers_) {
    it->AddNotify(worker_id);
  }
这样就对msg_wait_to_notify_[worker_id]增加了4次。
请问为啥不是wokers[worker_Id]->AddNofify()，只对msg_wait_to_notify_加1 ？
麻烦大神给讲解一下，有点看不懂了。 :-)

**Comment by liyichao** [comment]
Thanks for reading the source.

It will not be added four times. `msg_wait_to_notify_` refers to different workers' `msg_wait_to_notify_`.
