### ISSUE TITLE
ae库的stop变量不是需要加个volatile吗

### ISSUE THREAD

**Issue by DongwenHuang** [zhihu/kids#54]
void Worker::Stop() {
  eventl_->stop = 1;
  void *ret;
  pthread_join(tid_, &ret);
}

大神，可以请教个问题吗，我看多线程访问了ae_loop的stop变量，不是需要把stop变量加个volatile防止编译器从寄存器里读取值导致死循环吗

**Comment by liyichao** [comment]
>A volatile specifier is a hint to a compiler that an object may change its value in ways not specified by the language so that aggressive optimizations must be avoided.

Volatile is not needed because it does not matter. If the worker thread reads a 0, at the next eventloop it will read a 1. Eventually, it will read the 1.
