### ISSUE TITLE
Parse config file error when set `flush 5s` in store file

### ISSUE THREAD

**Issue by zfjoy520** [zhihu/kids#56]
kids version is: 1.0.0
*.conf file is like this:

```
...
store file {
  path /data/kids/logs/[topic];
  name [date].log;
  flush 5s;
}
...
```
when start kids, I met:

```
2016/11/07 19:34:43 [FATAL] Parse config file error
Unkonw store field(19): flush 5s
```

could someone give me help, tks.

**Comment by liyichao** [comment]
Sorry, 1.0.0 does not have this feature. https://github.com/zhihu/kids/blob/1.0.0/src/conf.cc#L31
